### ISSUE TITLE
Facing issue when using with PKRevealController

### ISSUE THREAD

**Issue by mickeyckm** [kentnguyen/KNSemiModalViewController#30]
Hi,

I'm facing this error. Any idea how to fix it? 

2013-02-07 14:34:21.261 XXXX[1605:907] **\* Assertion failure in -[PKRevealController kn_optionsOrDefaultForKey:], /Users/xxxxxx/Work/xxxxx/codes/xxxxx/Pods/KNSemiModalViewController/Source/UIViewController+KNSemiModal.m:57
2013-02-07 14:34:21.263 XXXX[1605:907] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Defaults must have been set when accessing options.'

It happened when I tried to do this...
- (IBAction)done:(id)sender
  {
  UIViewController *parent = [self.view containingViewController];
  if ([parent respondsToSelector:@selector(dismissSemiModalView)]) {
      [parent dismissSemiModalView];
  }
  }

Cheers,
Mickey

**Comment by kentnguyen** [comment]
Could you try manually copy the 4 source files to your project?

**Comment by ghost** [comment]
I have exactly the same problem when I dismissed a UINavigationController. Any idea how to fix it?

Best regards,
Jens

**Comment by kentnguyen** [comment]
could you send some source code? are u using cocopod? try adding the
library manually from master

On Sunday, March 3, 2013, jmarq23 wrote:

> I have exactly the same problem when I dismissed a UINavigationController.
> Any idea how to fix it?
> 
> Best regards,
> Jens
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kentnguyen/KNSemiModalViewController/issues/30#issuecomment-14346647
> .

## 

Regards,
Kent Nguyen

**Comment by ghost** [comment]
Ok, I have tried both, but nothing works.

Update: It works! :)

**Comment by kentnguyen** [comment]
please send some sample code

**Comment by ghost** [comment]
Yep, but that is a little bit confused.

The master branch contains 4 files: 
- NSObject+YMOptionsAndDefaults.h
- NSObject+YMOptionsAndDefaults.m
- UIViewController+KNSemiModal.h
- UIViewController+KNSemiModal.m

When I add these files to my project and I use the library to my UINavigationController views are push correctly. However the button on the UINavigationBar crashes the app after click on them. 

Debug area shows following:

```
2013-03-04 20:23:19.260 App[71247:c07] *** Assertion failure in -[StreamViewController ym_optionOrDefaultForKey:], /path/to/project/folder/NSObject+YMOptionsAndDefaults.m:24
2013-03-04 20:23:19.264 App[71247:c07] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Defaults must have been set when accessing options.'
```

It happend when I tried to do this: 

```
self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Done" style:UIBarButtonItemStyleBordered target:nil action:@selector(dismissSemiModalView)];
```

or this:

```
- (void)dismissSettingsView:(id)sender
{   
    UIViewController *parent = [self.view containingViewController];
    if ([parent respondsToSelector:@selector(dismissSemiModalView)])
    {
        [parent dismissSemiModalView];
    }
}
```

---

Otherwise when I use CocoaPods to add this library to my project there are only 2 files:
- UIViewController+KNSemiModal.h
- UIViewController+KNSemiModal.m

The button on the UINavigationBar works and the UINavigationController is dismissed correctly. But the UINavigationController stops pushing views without any error or something else.

---

I hope that helps. If not I can provide my Xcode project with you. Let me know if you are interested.

Best regards

**Comment by kentnguyen** [comment]
Yes please send your entire Xcode project. Perhaps there are settings that are not within the code itself.

**Comment by ghost** [comment]
Here you can download the project:
https://www.dropbox.com/s/04lv7ib3yl3svab/modalexample.zip

**Comment by kentnguyen** [comment]
Thanks, I have _kind of_ fixed the issue. The problem is not really with my code but your code. You call `dismissSemiModalView` on the wrong controller, this is because you have a UINavigationController in the middle of the hierarchy.

Anyway, I have added new code to make it more convenient for almost all use case:
- You can call `dismissSemiModalView` from the parent/presenting controller if you still have the object reference
- or you can call that directly from the child controller being presented

**Comment by mickeyckm** [comment]
Is this new version in Cocoapods?

**Comment by kentnguyen** [comment]
Not yet. Please get the code from this repo

**Comment by mRs-** [comment]
i updated the CocoaPods Repo for this.
