### ISSUE TITLE
Addition: SlideDown

### ISSUE THREAD

**Issue by philhinco** [kentnguyen/KNSemiModalViewController#40]
Hi,

I was playing around with your SemiModalViewController and sadly found out that there is no transition style that lets the modal view slide down from above.

Is it possible to add something like that?

**Comment by fprosper** [comment]
Yes, I am also interested in that, because I plan to have some UITextFields on the modal UIViewController and they need room for an inputView. Looking at the implementation of your classes I suppose that having the modal UIViewController slide from above would be quite difficult to achieve I guess...

**Comment by kentnguyen** [comment]
Sorry, won't support this feature. It would be quite a different kind of transaction which involves hiding of status bar as well.

**Comment by fprosper** [comment]
Thanks anyway, cheers.
