### ISSUE TITLE
Is it possible to present semi UIViewController with some space above?

### ISSUE THREAD

**Issue by mixdesign** [kentnguyen/KNSemiModalViewController#56]
Great library, thank you!
When I try to present UINavigationController with presentSemiViewController, the UINavigationController covers all screen, but I want it to present semily as method says.
Please look at screenshot (The wunderlist app do what I want):
https://www.monosnap.com/image/DaubNUql9mn1ArPC3qbmHLgCm

**Comment by kentnguyen** [comment]
It’s not a good idea to present UINav with this library, maybe you could reconsider using a fake navbar instead of a real one.

**Comment by mixdesign** [comment]
Is there any explanation why it's not a good idea for this library. Maybe I missed some discussions. 
I think it would be a good feature for this library :)

**Comment by kentnguyen** [comment]
The idea of the library is to present a semi modal which is a lightweight interaction modal. Your modal of course could contain anything but since it's a 'modal' it should only be supplementary to the main view behind. If you have UINav stack and several other actions require user input, then maybe it's better to rethink how you present such options to user.

**Comment by mixdesign** [comment]
I agree. Thank you.
